# Generated by Django 3.1.7 on 2021-04-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCommonInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('job_profession', models.CharField(blank=True, max_length=20)),
                ('job_address', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.CharField(blank=True, max_length=20)),
                ('vehicle_no', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=20)),
                ('family_member', models.CharField(max_length=20)),
                ('contactno', models.CharField(max_length=13)),
                ('home_pic', models.FileField(blank=True, default='home.jpg', upload_to='img/')),
            ],
        ),
    ]
