# Generated by Django 3.1.7 on 2021-04-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0002_membercommoninformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(blank=True, default='default.jpg', upload_to='img/')),
                ('m_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='chairman.membercommoninformation')),
                ('user_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='chairman.user')),
            ],
        ),
    ]
