# Generated by Django 3.1.7 on 2021-04-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0003_chairman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(default='not Found In Record', max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(default='not Found In Record', max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('post_uploaded_pic', models.FileField(blank=True, default='default.jpg', upload_to='img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='Not Provided Yet', max_length=20)),
                ('lname', models.CharField(default='Not Provided Yet', max_length=20)),
                ('contactno', models.CharField(max_length=13)),
                ('profile_pic', models.FileField(blank=True, default='default.jpg', upload_to='img/')),
                ('user_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='chairman.user')),
            ],
        ),
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='Not Provided Yet', max_length=20)),
                ('lname', models.CharField(default='Not Provided Yet', max_length=20)),
                ('profile_pic', models.FileField(blank=True, default='default.jpg', upload_to='img/')),
                ('m_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='chairman.membercommoninformation')),
                ('user_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='chairman.user')),
            ],
        ),
    ]
